# 项目相关配置
my-blog-java:
  # 名称
  name: my-blog-java
  # 版本
  version: 1.0.0
  # 版权年份
  copyrightYear: 2020
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数组计算 char 字符验证
  captchaType: math

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat 的 URI 编码
    uri-encoding: UTF-8

# 日志配置
logging:
  level:
    com.qiufeng: debug
    org.springframework: warn

# Spring 配置
spring:
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles:
    active: dev
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size:  10MB
      # 设置总上传的文件大小
      max-request-size:  20MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  # redis 配置
  redis:
    # 地址
    host: localhost
    # 端口，默认为6379
    port: 6379
    # 密码
    password:
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

## token配置
#token:
#  # 令牌自定义标识
#  header: Authorization
#  # 令牌密钥
#  secret: abcdefghijklmnopqrstuvwxyz
#  # 令牌有效期（默认30分钟）
#  expireTime: 30
#  # 前缀
#  prefix: 'Bearer '
#  # 内容
#  subject: congge
#  # 过期时间
#  expirition: 1000 * 24 * 60 * 7
#  appsecretKey: congge_secret
#  roleClaims: rol

# MyBatis配置
mybatis:
  # 搜索指定包别名
  type-aliases-package: com.qiufeng.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapper-locations: classpath:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  config-location: classpath:mybatis/mybatis-config.xml

## PageHelper分页插件
#pagehelper:
#  auto-dialect: mysql
#  reasonable: true
#  support-methods-arguments: true
#  params: count=countSql

## Swagger配置
#swagger:
#  # 是否开启swagger
#  enabled: true
#  # 请求前缀
#  pathMapping: /dev-api

## 防止XSS攻击
#xss:
#  # 过滤开关
#  enabled: true
#  # 排除链接（多个用逗号分隔）
#  excludes: /system/notice/*
#  # 匹配链接
#  urlPatterns: /system/*,/monitor/*,/tool/*
# 验证码session头


